server:
  port: 8080

spring:
  application:
    name: order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置nacos 地址
        namespace: 6172af31-62f0-487a-8694-469c3fe5cf3d
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: '*'  #暴露监控的东西