server:
  port: 8001

spring:
  application:
    name: payment8001
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置nacos 地址
        namespace: 6172af31-62f0-487a-8694-469c3fe5cf3d
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource     #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver     # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/cloud2020?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  banner:
    charset: UTF-8
    location: classpath:config/banner.txt
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.kyee.cloud.entities #所有Entity别名类所在包

management:
  endpoints:
    web:
      exposure:
        include: '*'  #暴露监控的东西